default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: task-manager_development

test:
  adapter: mysql2
  encoding: utf8
  database: task-manager_test
  username: travis
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>
