# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80ad33ae361f2c471f0d440449d74af6d2d49bee57b344b9beee8392e153bdc633600b4585d40329589a87f12870bad8e0f81ecd254b49f299ceaa3048edda9

test:
  secret_key_base: 4e944009bfad76fe5f52095e3e3d565ac3eed3700243fb78a497f2bee236ee5269ac4f20fa003fdc053b22b677b3ec6d2d4cc301d49fcfe38356d74848388bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
